"""
	6.	Find the Difference 

	Given two strings s and t which consist of only lowercase letters.
	String t is generated by random shuffling string s and then add one more letter at a random position.
	Find the letter that was added in t.
	Example: 
		Input:
			s = "abcd"
			t = "abcde"
		Output:
			e
		Explanation:
			'e' is the letter that was added.
"""

def findDifference(s,t):
	ss = {si for si in s}
	for ti in t:
		if not ti in ss:
			return ti
	return ""
	

		

if __name__ == "__main__":
	s = "abcd"
	t = "abcde"
	print(findDifference(s,t))